#!/bin/bash
export HOME=/app
cd /app

for file in .profile.d/*.sh; do
  source $file
done
hash -r

case "$(basename $0)" in
  start)
    if [[ -f Procfile ]]; then
      command="$(ruby -e "require 'yaml';puts YAML.load_file('Procfile')['$1']")"
    else
      command="$(ruby -e "require 'yaml';puts (YAML.load_file('.release')['default_process_types'] || {})['$1']")"
    fi
    ;;
  *)
    command="$@"
    ;;
esac

$(eval echo ${command})
